AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Mimir S3 Storage and IRSA Role for Infrastructure Agent
  NIST 800-53 R5 Controls:
    - SC-28: Encryption at Rest (SSE-S3)
    - SC-8: Encryption in Transit (HTTPS only)
    - AU-9: Protection of Audit Information (versioning)
    - AC-6: Least Privilege (scoped IRSA policy)

Parameters:
  ProjectName:
    Type: String
    Default: infra-agent
  Environment:
    Type: String
    AllowedValues: [dev, tst, prd]
    Default: dev
  OidcProviderArn:
    Type: String
    Description: ARN of the EKS OIDC provider for IRSA
  OidcProviderUrl:
    Type: String
    Description: URL of the OIDC provider (without https://)
  RetentionDays:
    Type: Number
    Default: 30
  Owner:
    Type: String
    Default: platform-team
  IaCVersion:
    Type: String
    Default: '1.0.0'

Resources:
  MimirBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      BucketName: !Sub '${ProjectName}-${Environment}-mimir-${AWS::AccountId}'
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
            BucketKeyEnabled: true
      VersioningConfiguration:
        Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      LifecycleConfiguration:
        Rules:
          - Id: TransitionToIA
            Status: Enabled
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: !Ref RetentionDays
          - Id: ExpireOldVersions
            Status: Enabled
            NoncurrentVersionExpiration:
              NoncurrentDays: 90
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-mimir'
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: IaC_Version
          Value: !Ref IaCVersion
        - Key: NIST_Control
          Value: SC-28_AU-9
        - Key: Purpose
          Value: mimir-metrics-storage

  MimirBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref MimirBucket
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: DenyNonHTTPS
            Effect: Deny
            Principal: '*'
            Action: 's3:*'
            Resource:
              - !Sub '${MimirBucket.Arn}'
              - !Sub '${MimirBucket.Arn}/*'
            Condition:
              Bool:
                'aws:SecureTransport': 'false'
          - Sid: AllowMimirRole
            Effect: Allow
            Principal:
              AWS: !GetAtt MimirRole.Arn
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Resource:
              - !Sub '${MimirBucket.Arn}'
              - !Sub '${MimirBucket.Arn}/*'

  MimirRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-${Environment}-mimir-role'
      Description: IRSA role for Mimir to access S3 storage
      AssumeRolePolicyDocument:
        Fn::Sub:
          - |
            {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Effect": "Allow",
                  "Principal": {
                    "Federated": "${OidcArn}"
                  },
                  "Action": "sts:AssumeRoleWithWebIdentity",
                  "Condition": {
                    "StringEquals": {
                      "${OidcUrl}:sub": "system:serviceaccount:observability:mimir",
                      "${OidcUrl}:aud": "sts.amazonaws.com"
                    }
                  }
                }
              ]
            }
          - OidcArn: !Ref OidcProviderArn
            OidcUrl: !Ref OidcProviderUrl
      Tags:
        - Key: Name
          Value: !Sub '${ProjectName}-${Environment}-mimir-role'
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: IaC_Version
          Value: !Ref IaCVersion
        - Key: NIST_Control
          Value: AC-6

  MimirPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub '${ProjectName}-${Environment}-mimir-s3-policy'
      Roles:
        - !Ref MimirRole
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: MimirS3Access
            Effect: Allow
            Action:
              - 's3:PutObject'
              - 's3:GetObject'
              - 's3:DeleteObject'
            Resource: !Sub '${MimirBucket.Arn}/*'
          - Sid: MimirS3List
            Effect: Allow
            Action:
              - 's3:ListBucket'
              - 's3:GetBucketLocation'
            Resource: !Sub '${MimirBucket.Arn}'

Outputs:
  MimirBucketName:
    Value: !Ref MimirBucket
    Export:
      Name: !Sub '${ProjectName}-${Environment}-mimir-bucket-name'
  MimirRoleArn:
    Value: !GetAtt MimirRole.Arn
    Export:
      Name: !Sub '${ProjectName}-${Environment}-mimir-role-arn'
